# Generated by Django 4.1 on 2022-08-22 05:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('bio', models.TextField(null=True)),
                ('phone_no', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='\\d{10}')])),
                ('profile_pic', models.ImageField(upload_to='profile_pic/')),
            ],
        ),
    ]
