# Generated by Django 4.1 on 2022-08-22 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='updated_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='username',
            field=models.CharField(default='', max_length=254, unique=True),
        ),
    ]
